apiVersion: v1
kind: Service
metadata:
  name: kanflow-backend
  namespace: kanflow
spec:
  selector:
    app: kanflow-backend
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
