version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"  # or the port your frontend uses
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/kanflow
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
