- name: Install required dependencies
  become: true
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Check if Helm is already installed (via file check)
  stat:
    path: /usr/local/bin/helm
  register: helm_check

- name: Download Helm archive if not already installed
  become: true
  shell: |
    curl -fsSL -o /tmp/helm.tar.gz https://get.helm.sh/helm-v3.14.2-linux-amd64.tar.gz
  when: not helm_check.stat.exists
  args:
    executable: /bin/bash

- name: Extract Helm binary
  become: true
  unarchive:
    src: "/tmp/helm.tar.gz"
    dest: "/tmp/"
    remote_src: yes
  when: not helm_check.stat.exists

- name: Move Helm binary to install directory
  become: true
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/helm"
    mode: '0755'
    remote_src: yes
  when: not helm_check.stat.exists

- name: Verify Helm installation
  command: helm version --short
  register: helm_output
  changed_when: false

- name: Print Helm version
  debug:
    var: helm_output.stdout
