pipeline {
  agent any

  environment {
    DOCKER_IMAGE = 'aamir017/kanflow-backend'
    DOCKER_TAG = 'latest'
    ANSIBLE_HOST_KEY_CHECKING = 'False'
  }

  stages {

    stage('Checkout Code') {
      steps {
        git branch: 'main', url: 'https://github.com/Aamir017/Kanflow.git'
      }
    }

    stage('Security Scan (Trivy)') {
      steps {
        sh '''
          echo "🔎 Setting up Trivy..."
          mkdir -p ~/.local/bin

          if ! command -v trivy > /dev/null; then
            echo "📦 Installing Trivy..."
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ~/.local/bin
          fi

          echo "🔍 Scanning Docker image for CRITICAL vulnerabilities..."
          ~/.local/bin/trivy image --exit-code 0 --severity CRITICAL $DOCKER_IMAGE:$DOCKER_TAG || echo "⚠️ Vulnerabilities found"
        '''
      }
    }

    stage('Deploy with Ansible') {
      steps {
        sh '''
          echo "🚀 Running Ansible playbook..."

          cd Kanflow/ansible
          
          if ! command -v ansible-playbook > /dev/null; then
            echo "❌ Ansible not found. Please install Ansible on Jenkins agent."
            exit 1
          fi

          ansible-playbook -i inventory.ini playbook.yml
        '''
      }
    }

    stage('Notify') {
      steps {
        echo '✅ Pipeline completed!'
      }
    }
  }

  post {
    success {
      echo '🎉 Success: App deployed!'
    }
    failure {
      echo '❌ Error: Pipeline failed'
    }
  }
}
