pipeline {
  agent any

  environment {
    DOCKER_IMAGE = 'aamir017/kanflow-backend'
    DOCKER_TAG = 'latest'
    ANSIBLE_HOST_KEY_CHECKING = 'False'
  }

  stages {

    stage('Checkout Code') {
      steps {
        git branch: 'main', url: 'https://github.com/Aamir017/Kanflow.git'
      }
    }

    stage('Security Scan (Trivy)') {
      steps {
        sh '''
          if ! command -v trivy > /dev/null; then
            echo "📦 Installing Trivy..."
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          fi
          trivy image --exit-code 0 --severity CRITICAL $DOCKER_IMAGE:$DOCKER_TAG || echo "⚠️ Vulnerabilities found"
        '''
      }
    }

    stage('Deploy (Ansible)') {
      steps {
        dir('ansible') {
          sh 'ansible-playbook -i inventory.ini playbook.yml'
        }
      }
    }

    stage('Notify') {
      steps {
        echo '✅ Pipeline completed!'
      }
    }

  }

  post {
    success {
      echo '🎉 Success: App deployed!'
    }
    failure {
      echo '❌ Error: Pipeline failed'
    }
  }
}

